server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    schemas:
      catalogue
  security:
    user:
      name: catalogue-service-user
      password: password
      roles:
        - SERVICE



logging:
  level:
    sql: info


data-source:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres